DELETE http://localhost:3003/api/events/60f8344ce866de8404db90b1 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2MGY4MDBjMDFiMmY5Nzc4YWNhZTYyMDkiLCJpYXQiOjE2MjY4ODAxMDV9.VI5qXf2bdOOYFVi-vjRJvUg29M8PbqcJSKfKSToVc-4