DELETE http://localhost:3003/api/events/60f949d0337c8f76b4a90baf 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2MGY4MDBjMDFiMmY5Nzc4YWNhZTYyMDkiLCJpYXQiOjE2MjY4ODAxMDV9.VI5qXf2bdOOYFVi-vjRJvUg29M8PbqcJSKfKSToVc-4