GET http://localhost:3003/api/events/ 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2MGY4MDBjMDFiMmY5Nzc4YWNhZTYyMDkiLCJpYXQiOjE2MjY4Nzk4MzJ9.mU4M0kuYFARCp0VqNRTTwJWBVermFlT6oXPl_A2at2U